name = "CodingTheory"
uuid = "89c41d41-0018-4667-9435-0b7cbc9fb764"
authors = ["Jake W. Ireland <jakewilliami@icloud.com> and contributors"]
version = "0.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
Polynomials = "1.1.9"
Primes = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
